const SUPABASE_URL='https://gvyeooqemajnvfbgnagv.supabase.co';
const SUPABASE_KEY='sb_publishable_moYDSTJplgl9XPCiKR96bQ_CPt3MJ7z';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const KEY='space-mining-v6';
const WORLDS=[
['🌑','Astéroïde Nova',0,1],['🔴','Mars',1e6,2.1],['🪐','Saturne',5e7,5],['💠','Nébuleuse Azur',5e9,12],['🌌','Trou noir',5e11,30],['☀️','Étoile Helios',5e13,85],['🌀','Dimension X',1e16,280]
];
const BUILDINGS=['Foreuse laser','Robot mineur','Raffinerie orbitale','Station minière','Flotte de cargos','Extracteur gravitationnel','Collecteur Dyson','Portail quantique','Forge antimatière','Anneau de singularité'];
const ICONS=['🔧','🤖','🏭','🛰️','🚚','🧲','☀️','🌀','⚛️','💫'];
const RESEARCH=[
['click1','Laser de précision',2.5e6,'+20% clic'],['auto1','IA minière',2.5e8,'+25% production auto'],['global1','Réacteur quantique',1e10,'x1.20 production'],['discount','Logistique interplanétaire',5e11,'-4% prix bâtiments'],['auto2','Nanobots industriels',2e13,'+45% production auto'],['global2','Moteur de singularité',5e14,'x1.35 production'],['click2','Gant gravitationnel',1e15,'+35% clic'],['offline','Chrono-core',5e16,'hors-ligne jusqu’à 12h']];
let s=load(); let tab='planets'; let mineLock=false; let lastRender=0; let comboTimer=0; let lastSync=0;
function fresh(){let buildings={};WORLDS.forEach((_,w)=>BUILDINGS.forEach((_,b)=>buildings[w+'-'+b]=0));return{money:0,total:0,prestige:0,buildings,research:{},missions:{},xp:0,level:1,nickname:'Mineur',last:Date.now(),combo:0,online:false}}
function load(){try{let x=null;for(const k of [KEY,'space-mining-v5','space-mining-v4','space-mining-v3','space-mining-v2']){const raw=localStorage.getItem(k);if(raw){x=JSON.parse(raw);break}}let z=Object.assign(fresh(),x||{});let base=fresh();z.buildings=Object.assign(base.buildings,z.buildings||{});z.research=z.research||{};z.missions=z.missions||{};z.nickname=z.nickname||'Mineur';return z}catch{return fresh()}}
function save(){s.last=Date.now();localStorage.setItem(KEY,JSON.stringify(s))}
function fmt(n){if(!Number.isFinite(n))return '∞';let a=Math.abs(n);if(a<1000)return Math.floor(n).toLocaleString('fr-FR');let u=['K','M','Md','Bn','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];let i=Math.floor(Math.log10(a)/3);return (n/Math.pow(1000,i)).toFixed(i>3?2:1)+' '+(u[i-1]||'e'+i*3)}
function mult(){let m=1+0.12*s.prestige;if(s.research.global1)m*=1.2;if(s.research.global2)m*=1.35;return m}
function clickPower(){return 1*(s.research.click1?1.2:1)*(s.research.click2?1.35:1)*mult()*(1+Math.min(0.5,s.combo*.025))}
function autoRate(){let r=0;WORLDS.forEach((w,wi)=>BUILDINGS.forEach((_,bi)=>{let n=s.buildings[wi+'-'+bi]||0;r+=n*baseProd(wi,bi)}));r*=mult()*(s.research.auto1?1.25:1)*(s.research.auto2?1.45:1);return r}
function baseProd(w,b){return (1+w*1.7)*Math.pow(10,w*2)*(b===0?2:Math.pow(3,b))}
function cost(w,b){let n=s.buildings[w+'-'+b]||0;let base=(w+1)*100*Math.pow(12,w)*Math.pow(4,b);return base*Math.pow(1.225,n)*(s.research.discount?.96:1)}
function gain(x){s.money+=x;s.total+=x;s.xp+=Math.max(1,Math.floor(Math.log10(Math.max(10,x))));levelCheck()}
function levelCheck(){let nl=Math.floor(Math.sqrt(s.xp/50))+1;if(nl>s.level){s.level=nl;toast('🎉 Niveau '+nl)} }
function mine(){if(mineLock)return;mineLock=true;let now=performance.now();gain(clickPower());s.combo=Math.min(12,s.combo+1);comboTimer=Date.now()+1600;if(now-lastRender>90){render();lastRender=now}else requestAnimationFrame(()=>{if(performance.now()-lastRender>90){render();lastRender=performance.now()}});setTimeout(()=>mineLock=false,18)}
function buy(w,b){let c=cost(w,b);if(s.money<c){toast('💸 Il manque '+fmt(c-s.money));return}s.money-=c;s.buildings[w+'-'+b]=(s.buildings[w+'-'+b]||0)+1;s.xp+=10;render()}
function worldUnlocked(w){return w===0||s.total>=WORLDS[w][2]}
function worldDone(w){return worldUnlocked(w)&&BUILDINGS.every((_,b)=>(s.buildings[w+'-'+b]||0)>=10)}
function doResearch(id){let r=RESEARCH.find(x=>x[0]===id);if(!r||s.research[id]||s.money<r[2])return;s.money-=r[2];s.research[id]=true;toast('🧪 '+r[1]+' débloquée');render()}
function missions(){let defs=[['click100','Premier forage',100,1e4],['build50','Industrialisation',50,1e7],['total1','Premier milliard',1e9,1e9],['world3','Saturne',1,5e8],['world7','Dimension X',1,1e16]];return defs}
function missionValue(id){if(id==='click100')return Math.min(s.total,100);if(id==='build50')return Object.values(s.buildings).reduce((a,b)=>a+b,0);if(id==='total1')return Math.min(s.total,1e9);if(id==='world3')return worldDone(2)?1:0;if(id==='world7')return worldDone(6)?1:0}
function claim(id,need,reward){if(s.missions[id]||missionValue(id)<need)return;s.missions[id]=true;gain(reward);toast('🎯 +'+fmt(reward));render()}
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1400)}
function render(){document.getElementById('total').textContent=fmt(s.total);document.getElementById('rate').textContent=fmt(autoRate())+'/s';document.getElementById('prestige').textContent='P'+s.prestige;document.getElementById('clickPower').textContent='+'+fmt(clickPower());document.getElementById('combo').textContent=s.combo;renderTab();}
function renderTab(){if(tab==='planets')renderPlanets();if(tab==='research')renderResearch();if(tab==='missions')renderMissions();if(tab==='rank')renderRank()}
function renderPlanets(){let out='';WORLDS.forEach((w,wi)=>{let ok=worldUnlocked(wi);let done=worldDone(wi);out+=`<article class="world ${ok?'':'locked'}"><div class="world-head"><div><h2>${w[0]} ${w[1]}</h2><small>${wi?`Seuil: ${fmt(w[2])} · multiplicateur x${w[3]}`:'Point de départ · x1'}</small></div><span class="badge">${done?'COMPLÈTE':ok?'DÉBLOQUÉE':'VERROUILLÉE'}</span></div><div class="buildings">`;BUILDINGS.forEach((name,b)=>{let n=s.buildings[wi+'-'+b]||0,c=cost(wi,b);out+=`<div class="building"><div><strong>${ICONS[b]} ${name}</strong><small>${fmt(baseProd(wi,b))}/s · possédé: ${n}</small></div><button class="buy" data-w="${wi}" data-b="${b}" ${!ok||s.money<c?'disabled':''}>${fmt(c)}<br>ACHETER</button></div>`});out+='</div></article>'});document.getElementById('tab-planets').innerHTML=out}
function renderResearch(){let out='<div class="panel"><b>Recherches équilibrées</b><small style="color:var(--muted);display:block;margin-top:5px">Les bonus sont volontairement modérés : la progression vient surtout de l’investissement.</small></div>';RESEARCH.forEach(r=>{let owned=s.research[r[0]];out+=`<div class="research"><div><strong>${owned?'✅':'🧪'} ${r[1]}</strong><small>${r[3]}</small></div><button class="buy" data-r="${r[0]}" ${owned||s.money<r[2]?'disabled':''}>${owned?'ACQUISE':fmt(r[2])}</button></div>`});document.getElementById('tab-research').innerHTML=out}
function renderMissions(){let out='';missions().forEach(m=>{let v=missionValue(m[0]),done=s.missions[m[0]];out+=`<div class="mission"><strong>${done?'✅':'🎯'} ${m[1]}</strong><small>${fmt(v)} / ${fmt(m[2])} · récompense ${fmt(m[3])}</small><div class="bar"><i style="width:${Math.min(100,v/m[2]*100)}%"></i></div><button class="buy" data-m="${m[0]}" data-need="${m[2]}" data-reward="${m[3]}" ${done||v<m[2]?'disabled':''}>${done?'RÉCLAMÉ':'RÉCLAMER'}</button></div>`});let req=WORLDS.every((_,i)=>worldDone(i))&&Object.values(s.buildings).every(n=>n>=10);let need=2e15*Math.pow(12,s.prestige);out+=`<div class="mission"><strong>👑 Prestige ${s.prestige+1}</strong><small>Terminer les 7 planètes, 10 de chaque bâtiment et atteindre ${fmt(need)} crédits. Bonus permanent +12%.</small><button class="buy" id="prestigeBtn" ${req&&s.total>=need?'':'disabled'}>PRESTIGE</button></div>`;document.getElementById('tab-missions').innerHTML=out}
async function renderRank(){document.getElementById('tab-rank').innerHTML='<div class="panel">☁️ Chargement du classement mondial…</div>';try{let {data,error}=await sb.from('leaderboard').select('nickname,total,prestige,level').order('total',{ascending:false}).order('prestige',{ascending:false}).order('level',{ascending:false}).limit(100);if(error)throw error;let out='<div class="panel"><b>🏆 TOP 100 MONDIAL</b><small style="display:block;color:var(--muted);margin-top:4px">Classement cloud Supabase</small></div>';(data||[]).forEach((r,i)=>out+=`<div class="rank-row"><div class="pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div><strong>${esc(r.nickname)}</strong><small>Niveau ${r.level} · Prestige ${r.prestige}</small></div><b>${fmt(Number(r.total))}</b></div>`);document.getElementById('tab-rank').innerHTML=out}catch(e){document.getElementById('tab-rank').innerHTML='<div class="panel">⚠️ Classement indisponible. Le jeu continue en local.</div>'}}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function ensureAuth(){let {data}=await sb.auth.getSession();if(data.session){s.online=true;return data.session}let r=await sb.auth.signInAnonymously();if(r.error){s.online=false;throw r.error}s.online=true;return r.data.session}
async function syncCloud(){if(Date.now()-lastSync<5000)return;lastSync=Date.now();try{let session=await ensureAuth();if(!session)return;let {error}=await sb.functions.invoke('game-sync',{body:{nickname:s.nickname,total:s.total,prestige:s.prestige,level:s.level,xp:s.xp,state:s}});if(error)throw error;s.online=true}catch(e){s.online=false;console.warn(e)}}
async function loadCloud(){try{let session=await ensureAuth();if(!session)return;let {data,error}=await sb.from('player_state').select('state').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(data?.state){let localTotal=s.total;let cloud=data.state;if(Number(cloud.total||0)>localTotal)s=Object.assign(fresh(),cloud);else s.online=true}let {data:p}=await sb.from('profiles').select('nickname').eq('user_id',session.user.id).maybeSingle();if(p?.nickname)s.nickname=p.nickname;save();await syncCloud()}catch(e){console.warn('Cloud auth unavailable',e)}}
async function saveProfile(){let n=document.getElementById('nickname').value.trim().slice(0,20)||'Mineur';s.nickname=n;save();await syncCloud();document.getElementById('authStatus').textContent=s.online?'☁️ Profil synchronisé':'📱 Profil local';toast(s.online?'☁️ Profil enregistré':'Profil local enregistré')}
function prestige(){let need=2e15*Math.pow(12,s.prestige);let req=WORLDS.every((_,i)=>worldDone(i))&&Object.values(s.buildings).every(n=>n>=10)&&s.total>=need;if(!req)return;let p=s.prestige+1;s=fresh();s.prestige=p;s.nickname=localStorage.getItem('sm-nick')||'Mineur';save();toast('👑 Prestige '+p+' !');render();syncCloud()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.id==='mineBtn')return;if(b.dataset.tab){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.getElementById('tab-'+b.dataset.tab).classList.add('active');tab=b.dataset.tab;renderTab();return}if(b.dataset.w)buy(+b.dataset.w,+b.dataset.b);if(b.dataset.r)doResearch(b.dataset.r);if(b.dataset.m)claim(b.dataset.m,+b.dataset.need,+b.dataset.reward);if(b.id==='prestigeBtn')prestige()});
document.getElementById('mineBtn').addEventListener('pointerup',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();mine()});document.getElementById('mineBtn').addEventListener('click',e=>e.preventDefault());
document.getElementById('accountBtn').onclick=()=>{document.getElementById('nickname').value=s.nickname;document.getElementById('authStatus').textContent=s.online?'☁️ Connecté au cloud':'📱 Mode local';document.getElementById('accountModal').classList.remove('hidden')};document.getElementById('closeAccount').onclick=()=>document.getElementById('accountModal').classList.add('hidden');document.getElementById('saveProfile').onclick=saveProfile;document.getElementById('guestBtn').onclick=async()=>{try{await ensureAuth();s.online=true;await syncCloud();document.getElementById('authStatus').textContent='☁️ Connecté au cloud';toast('☁️ Compte invité connecté')}catch(e){toast('⚠️ Active les comptes anonymes Supabase')}};
setInterval(()=>{if(Date.now()>comboTimer&&s.combo){s.combo=0;render()}let r=autoRate()/4;gain(r);if(Date.now()-lastRender>450){render();lastRender=Date.now()}},250);
setInterval(()=>{save();syncCloud()},4000);window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});
function applyOffline(){let elapsed=Math.max(0,Date.now()-(s.last||Date.now()));let cap=s.research.offline?12*3600*1000:4*3600*1000;let sec=Math.min(elapsed,cap)/1000;if(sec>30){let bonus=autoRate()*sec;if(bonus>0){s.money+=bonus;s.total+=bonus;toast('🌙 Hors-ligne +'+fmt(bonus))}}s.last=Date.now();save()}
applyOffline();loadCloud();render();
