const SUPABASE_URL='https://gvyeooqemajnvfbgnagv.supabase.co';
const SUPABASE_KEY='sb_publishable_moYDSTJplgl9XPCiKR96bQ_CPt3MJ7z';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const KEY='space-mining-v7';
const WORLDS=[['🌑','Astéroïde Nova',0,1],['🔴','Mars',1e6,2.1],['🪐','Saturne',5e7,5],['💠','Nébuleuse Azur',5e9,12],['🌌','Trou noir',5e11,30],['☀️','Étoile Helios',5e13,85],['🌀','Dimension X',1e16,280]];
const BUILDINGS=['Foreuse laser','Robot mineur','Raffinerie orbitale','Station minière','Flotte de cargos','Extracteur gravitationnel','Collecteur Dyson','Portail quantique','Forge antimatière','Anneau de singularité'];
const ICONS=['🔧','🤖','🏭','🛰️','🚚','🧲','☀️','🌀','⚛️','💫'];
const RESEARCH=[['click1','Laser de précision',2.5e6,'+20% clic'],['auto1','IA minière',2.5e8,'+25% production auto'],['global1','Réacteur quantique',1e10,'x1.20 production'],['discount','Logistique interplanétaire',5e11,'-4% prix bâtiments'],['auto2','Nanobots industriels',2e13,'+45% production auto'],['global2','Moteur de singularité',5e14,'x1.35 production'],['click2','Gant gravitationnel',1e15,'+35% clic'],['offline','Chrono-core',5e16,'hors-ligne jusqu’à 12h']];
const MISSIONS=[['click100','Premier forage',100,1e4],['build50','Industrialisation',50,1e7],['total1','Premier milliard',1e9,1e9],['world3','Saturne',1,5e8],['world7','Dimension X',1,1e16]];
let s=load();let currentScreen='mine';let selectedWorld=Math.max(0,Math.min(6,Number(localStorage.getItem('sm-world')||0)));let lastUi=0,lastCloud=0,comboUntil=0,toastTimer=0,syncing=false;
function fresh(){const buildings={};WORLDS.forEach((_,w)=>BUILDINGS.forEach((_,b)=>buildings[w+'-'+b]=0));return{money:0,total:0,prestige:0,buildings,research:{},missions:{},xp:0,level:1,nickname:'Mineur',last:Date.now(),combo:0,online:false}}
function load(){try{let raw=null;for(const k of [KEY,'space-mining-v6','space-mining-v5','space-mining-v4','space-mining-v3','space-mining-v2']){const v=localStorage.getItem(k);if(v){raw=JSON.parse(v);break}}const z=Object.assign(fresh(),raw||{}),base=fresh();z.buildings=Object.assign(base.buildings,z.buildings||{});z.research=z.research||{};z.missions=z.missions||{};z.nickname=z.nickname||'Mineur';return z}catch{return fresh()}}
function save(){s.last=Date.now();try{localStorage.setItem(KEY,JSON.stringify(s))}catch(e){console.warn('local save failed',e)}}
function fmt(n){if(!Number.isFinite(n))return '∞';const a=Math.abs(n);if(a<1000)return Math.floor(n).toLocaleString('fr-FR');const u=['K','M','Md','Bn','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];const i=Math.floor(Math.log10(a)/3);return (n/Math.pow(1000,i)).toFixed(i>3?2:1)+' '+(u[i-1]||'e'+i*3)}
function mult(){let m=1+.12*s.prestige;if(s.research.global1)m*=1.2;if(s.research.global2)m*=1.35;return m}
function clickPower(){return mult()*(s.research.click1?1.2:1)*(s.research.click2?1.35:1)*(1+Math.min(.5,s.combo*.025))}
function baseProd(w,b){return (1+w*1.7)*Math.pow(10,w*2)*(b===0?2:Math.pow(3,b))}
function autoRate(){let r=0;WORLDS.forEach((_,w)=>BUILDINGS.forEach((_,b)=>{r+=(s.buildings[w+'-'+b]||0)*baseProd(w,b)}));return r*mult()*(s.research.auto1?1.25:1)*(s.research.auto2?1.45:1)}
function cost(w,b){const n=s.buildings[w+'-'+b]||0;return (w+1)*100*Math.pow(12,w)*Math.pow(4,b)*Math.pow(1.225,n)*(s.research.discount?.96:1)}
function gain(x){if(!Number.isFinite(x)||x<=0)return;s.money+=x;s.total+=x;s.xp+=Math.max(1,Math.floor(Math.log10(Math.max(10,x))));levelCheck()}
function levelCheck(){const nl=Math.floor(Math.sqrt(s.xp/50))+1;if(nl>s.level){s.level=nl;toast('🎉 Niveau '+nl)}}
function worldUnlocked(w){return w===0||s.total>=WORLDS[w][2]}
function worldDone(w){return worldUnlocked(w)&&BUILDINGS.every((_,b)=>(s.buildings[w+'-'+b]||0)>=10)}
function missionValue(id){if(id==='click100')return Math.min(s.total,100);if(id==='build50')return Object.values(s.buildings).reduce((a,b)=>a+b,0);if(id==='total1')return Math.min(s.total,1e9);if(id==='world3')return worldDone(2)?1:0;if(id==='world7')return worldDone(6)?1:0;return 0}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1300)}
function uiHeader(){document.getElementById('total').textContent=fmt(s.total);document.getElementById('rate').textContent=fmt(autoRate())+'/s';document.getElementById('prestige').textContent='P'+s.prestige;document.getElementById('clickPower').textContent='+'+fmt(clickPower());document.getElementById('combo').textContent=s.combo;document.getElementById('profileName').textContent=s.nickname;document.getElementById('profileLevel').textContent=s.level;document.getElementById('profileXp').textContent=fmt(s.xp);document.getElementById('profileTotal').textContent=fmt(s.total);document.getElementById('profileStatus').textContent=s.online?'☁️ Connecté au cloud':'📱 Mode local';document.getElementById('onlineDot').textContent=s.online?'● CLOUD':'● LOCAL';document.getElementById('onlineDot').style.color=s.online?'var(--good)':'var(--warn)';document.getElementById('worldProgress').textContent=WORLDS.filter((_,i)=>worldUnlocked(i)).length+'/7 débloquée'+(WORLDS.filter((_,i)=>worldUnlocked(i)).length>1?'s':'');document.getElementById('researchProgress').textContent=Object.keys(s.research).length+'/8';document.getElementById('missionProgress').textContent=Object.keys(s.missions).length+'/5';document.getElementById('planetTotal').textContent=WORLDS.filter((_,i)=>worldUnlocked(i)).length+'/7';document.getElementById('minePlanetName').textContent=WORLDS[selectedWorld][1]}
function setScreen(name){if(!document.getElementById('screen-'+name))name='mine';currentScreen=name;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id==='screen-'+name));document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===name));if(name==='planets')renderPlanets();if(name==='research')renderResearch();if(name==='missions')renderMissions();if(name==='rank')renderRank();if(name==='profile')renderProfile();uiHeader()}
function renderPlanets(){const strip=document.getElementById('planetStrip');strip.innerHTML=WORLDS.map((w,i)=>`<button class="planet-chip ${i===selectedWorld?'active ':''}${worldUnlocked(i)?'':'locked'}" data-world="${i}"><strong>${w[0]} ${w[1]}</strong><small>${worldUnlocked(i)?'Débloquée':'🔒 '+fmt(w[2])}</small></button>`).join('');const w=WORLDS[selectedWorld],ok=worldUnlocked(selectedWorld),done=worldDone(selectedWorld);if(!ok){document.getElementById('planetDetail').innerHTML=`<div class="planet-card locked-card"><div style="font-size:38px">🔒</div><h3>${w[0]} ${w[1]}</h3><p>Atteins ${fmt(w[2])} crédits extraits pour débloquer cette planète.</p></div>`;return}let built=BUILDINGS.reduce((a,_,b)=>a+(s.buildings[selectedWorld+'-'+b]||0),0),max=100;document.getElementById('planetDetail').innerHTML=`<article class="planet-card"><div class="planet-head"><div><h3>${w[0]} ${w[1]}</h3><p>x${w[3]} · ${fmt(baseProd(selectedWorld,0))}/s de base · ${built}/100 bâtiments</p></div><span class="badge">${done?'COMPLÈTE':'ACTIVE'}</span></div><div class="building-list">${BUILDINGS.map((name,b)=>{const n=s.buildings[selectedWorld+'-'+b]||0,c=cost(selectedWorld,b);return `<div class="building"><div><strong>${ICONS[b]} ${name}</strong><small>${fmt(baseProd(selectedWorld,b))}/s · niveau ${n}</small></div><button class="buy" data-buy="${b}" ${s.money<c?'disabled':''}>${fmt(c)}<br>ACHETER</button></div>`}).join('')}</div><div style="padding:0 12px 13px"><small style="color:var(--muted);font-size:9px">Maîtrise de la planète</small><div class="progress"><i style="width:${built}%"></i></div></div></article>`}
function renderResearch(){document.getElementById('researchList').innerHTML=RESEARCH.map(r=>{const owned=!!s.research[r[0]];return `<article class="research-card"><div><strong>${owned?'✅':'🧪'} ${r[1]}</strong><small>${r[3]}</small></div><button class="buy" data-research="${r[0]}" ${owned||s.money<r[2]?'disabled':''}>${owned?'ACQUISE':fmt(r[2])}</button></article>`}).join('')}
function renderMissions(){document.getElementById('missionList').innerHTML=MISSIONS.map(m=>{const v=missionValue(m[0]),done=!!s.missions[m[0]],pct=Math.min(100,v/m[2]*100);return `<div class="mission-card"><strong>${done?'✅':'🎯'} ${m[1]}</strong><small>${fmt(v)} / ${fmt(m[2])} · récompense ${fmt(m[3])}</small><div class="bar"><i style="width:${pct}%"></i></div><button class="buy" data-mission="${m[0]}" ${done||v<m[2]?'disabled':''}>${done?'RÉCLAMÉ':'RÉCLAMER'}</button><div style="clear:both"></div></div>`}).join('');const need=2e15*Math.pow(12,s.prestige),req=WORLDS.every((_,i)=>worldDone(i))&&Object.values(s.buildings).every(n=>n>=10)&&s.total>=need;document.getElementById('prestigeCard').innerHTML=`<div class="prestige-card"><strong>👑 Prestige ${s.prestige+1}</strong><p>7 planètes complètes + 10 de chaque bâtiment + ${fmt(need)} crédits. Bonus permanent : +12%.</p><button class="buy" data-prestige="1" ${req?'':'disabled'}>PRESTIGE</button></div>`;document.getElementById('missionCount').textContent=Object.keys(s.missions).length+'/5'}
async function renderRank(){const box=document.getElementById('rankList');box.innerHTML='<div class="section-note">☁️ Chargement du classement mondial…</div>';document.getElementById('rankMe').textContent=s.online?'☁️ Ton profil est synchronisé':'📱 Tu joues actuellement en local';try{await ensureAuth();const {data,error}=await sb.from('leaderboard').select('nickname,total,prestige,level').order('total',{ascending:false}).order('prestige',{ascending:false}).order('level',{ascending:false}).limit(100);if(error)throw error;if(!data?.length){box.innerHTML='<div class="section-note">🏆 Tu peux être le premier du classement.</div>';return}box.innerHTML=data.map((r,i)=>`<div class="rank-row"><div class="pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div><strong>${esc(r.nickname)}</strong><small>Niveau ${r.level} · Prestige ${r.prestige}</small></div><b>${fmt(Number(r.total))}</b></div>`).join('')}catch(e){console.warn(e);box.innerHTML='<div class="section-note">⚠️ Classement temporairement indisponible. Ta partie locale continue sans blocage.</div>'}}
function renderProfile(){document.getElementById('nickname').value=s.nickname;document.getElementById('profileName').textContent=s.nickname}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderAll(){uiHeader();if(currentScreen==='planets')renderPlanets();else if(currentScreen==='research')renderResearch();else if(currentScreen==='missions')renderMissions();else if(currentScreen==='profile')renderProfile()}
function mine(){const now=performance.now();gain(clickPower());s.combo=Math.min(12,s.combo+1);comboUntil=Date.now()+1600;document.getElementById('combo').textContent=s.combo;document.getElementById('clickPower').textContent='+'+fmt(clickPower());document.getElementById('comboBar').style.width=(s.combo/12*100)+'%';if(now-lastUi>160){uiHeader();lastUi=now}}
function buyBuilding(b){const c=cost(selectedWorld,b);if(s.money<c){toast('💸 '+fmt(c-s.money)+' crédits manquants');return}s.money-=c;s.buildings[selectedWorld+'-'+b]=(s.buildings[selectedWorld+'-'+b]||0)+1;s.xp+=10;renderPlanets();uiHeader()}
function doResearch(id){const r=RESEARCH.find(x=>x[0]===id);if(!r||s.research[id]||s.money<r[2])return;s.money-=r[2];s.research[id]=true;toast('🧪 '+r[1]+' acquise');renderResearch();uiHeader()}
function claimMission(id){const m=MISSIONS.find(x=>x[0]===id);if(!m||s.missions[id]||missionValue(id)<m[2])return;s.missions[id]=true;gain(m[3]);toast('🎯 +'+fmt(m[3]));renderMissions();uiHeader()}
function doPrestige(){const need=2e15*Math.pow(12,s.prestige),req=WORLDS.every((_,i)=>worldDone(i))&&Object.values(s.buildings).every(n=>n>=10)&&s.total>=need;if(!req)return;const p=s.prestige+1,nick=s.nickname;s=fresh();s.prestige=p;s.nickname=nick;save();toast('👑 Prestige '+p+' !');renderAll();syncCloud(true)}
async function ensureAuth(){const {data}=await sb.auth.getSession();if(data.session){s.online=true;return data.session}const r=await sb.auth.signInAnonymously();if(r.error)throw r.error;s.online=true;return r.data.session}
async function syncCloud(force=false){if(syncing||(!force&&Date.now()-lastCloud<15000))return;syncing=true;lastCloud=Date.now();try{const session=await ensureAuth();const {error}=await sb.functions.invoke('game-sync',{body:{nickname:s.nickname,total:s.total,prestige:s.prestige,level:s.level,xp:s.xp,state:s}});if(error)throw error;s.online=true}catch(e){s.online=false;console.warn('cloud sync',e)}finally{syncing=false;uiHeader()}}
async function loadCloud(){try{const session=await ensureAuth();const {data,error}=await sb.from('player_state').select('state').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(data?.state&&Number(data.state.total||0)>s.total){const localNick=s.nickname;s=Object.assign(fresh(),data.state);s.nickname=s.nickname||localNick}const {data:p}=await sb.from('profiles').select('nickname').eq('user_id',session.user.id).maybeSingle();if(p?.nickname)s.nickname=p.nickname;s.online=true;save();uiHeader();await syncCloud(true)}catch(e){s.online=false;uiHeader();console.warn('cloud unavailable',e)}}
async function saveProfile(){s.nickname=(document.getElementById('nickname').value.trim()||'Mineur').slice(0,20);save();await syncCloud(true);toast(s.online?'☁️ Profil synchronisé':'📱 Profil local');renderProfile()}
function applyOffline(){const elapsed=Math.max(0,Date.now()-(s.last||Date.now())),cap=s.research.offline?43200000:14400000,sec=Math.min(elapsed,cap)/1000;if(sec>30){const bonus=autoRate()*sec;if(bonus>0){s.money+=bonus;s.total+=bonus;toast('🌙 Hors-ligne +'+fmt(bonus))}}s.last=Date.now();save()}
function resetGame(){if(!confirm('Réinitialiser toute la progression locale ?'))return;localStorage.removeItem(KEY);location.reload()}

document.addEventListener('pointerup',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='mineBtn'){if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();mine();return}if(b.dataset.go){e.preventDefault();setScreen(b.dataset.go);return}if(b.dataset.world){const i=Number(b.dataset.world);if(worldUnlocked(i)){selectedWorld=i;localStorage.setItem('sm-world',String(i));renderPlanets()}return}if(b.dataset.buy!==undefined){buyBuilding(Number(b.dataset.buy));return}if(b.dataset.research){doResearch(b.dataset.research);return}if(b.dataset.mission){claimMission(b.dataset.mission);return}if(b.dataset.prestige){doPrestige();return}if(b.id==='refreshRank'){renderRank();return}if(b.id==='accountBtn'){document.getElementById('modalStatus').textContent=s.online?'☁️ Connecté au cloud':'📱 Mode local';document.getElementById('modal').classList.remove('hidden');return}if(b.id==='closeModal'){document.getElementById('modal').classList.add('hidden');return}if(b.id==='modalGuest'){ensureAuth().then(()=>{s.online=true;toast('☁️ Cloud activé');document.getElementById('modalStatus').textContent='☁️ Connecté au cloud';syncCloud(true)}).catch(()=>toast('⚠️ Active Anonymous Sign-Ins dans Supabase'));return}if(b.id==='saveProfile'){saveProfile();return}if(b.id==='guestBtn'){ensureAuth().then(()=>{s.online=true;syncCloud(true)}).catch(()=>toast('⚠️ Active Anonymous Sign-Ins dans Supabase'));return}if(b.id==='resetBtn'){resetGame();return}} ,{passive:false});
document.getElementById('mineBtn').addEventListener('click',e=>e.preventDefault());
setInterval(()=>{if(Date.now()>comboUntil&&s.combo){s.combo=0;document.getElementById('combo').textContent='0';document.getElementById('comboBar').style.width='0%'}const r=autoRate()/4;gain(r);const now=performance.now();if(now-lastUi>500){uiHeader();if(currentScreen==='planets')document.getElementById('planetDetail').querySelectorAll('.buy').forEach(btn=>{const b=Number(btn.dataset.buy);btn.disabled=s.money<cost(selectedWorld,b)});lastUi=now}},250);
setInterval(()=>{save();syncCloud()},5000);window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();syncCloud(true)}});
applyOffline();uiHeader();setScreen('mine');loadCloud();
